var allSongs: any = [
  {
    artist: "Omah Lay",
    song: "Reason",
    album: "Single",
    time: 0,
    cover: "/cover/1.jpg",
    file: "/music/omhlayreason.mp3",
    playing: true,
  },
  {
    artist: "Yarden",
    song: "Wetin",
    album: "Single",
    time: 0,
    cover: "/cover/2.jpg",
    file: "/music/wetin.mp3",
    playing: false,
  },
  {
    artist: "Cinnamon Girl",
    song: "Lana Del Rey",
    album: "Single",
    time: 0,
    cover: "/cover/4.jpg",
    file: "/music/cinnamon.mp3",
    playing: false,
  },
  {
    artist: "Rihannah",
    song: "Consideration (feat. SZA)",
    album: "Single",
    time: 0,
    cover: "/cover/anti.jpg",
    file: "music/Consideration (feat. SZA).mp3",
    playing: false,
  },
  {
    artist: "Rihannah",
    song: "James Joint",
    album: "Single",
    time: 0,
    cover: "/cover/anti.jpg",
    file: "music/James Joint.mp3",
    playing: false,
  },
  {
    artist: "Rihannah",
    song: "Kiss It Better",
    album: "Single",
    time: 0,
    cover: "/cover/anti.jpg",
    file: "music/Kiss It Better.mp3",
    playing: false,
  },
  {
    artist: "Rihannah",
    song: "Work (feat. Drake)",
    album: "Single",
    time: 0,
    cover: "/cover/anti.jpg",
    file: "music/Work (feat. Drake).mp3",
    playing: false,
  },
  {
    artist: "Rihannah",
    song: "Desperado",
    album: "Single",
    time: 0,
    cover: "/cover/anti.jpg",
    file: "music/Desperado.mp3",
    playing: false,
  },
  {
    artist: "Rihannah",
    song: "Woo",
    album: "Single",
    time: 0,
    cover: "/cover/anti.jpg",
    file: "music/Woo.mp3",
    playing: false,
  },
  {
    artist: "Rihannah",
    song: "Needed Me",
    album: "Single",
    time: 0,
    cover: "/cover/anti.jpg",
    file: "music/Needed Me.mp3",
    playing: false,
  },
  {
    artist: "Rihannah",
    song: "Yeah, I Said It",
    album: "Single",
    time: 0,
    cover: "/cover/anti.jpg",
    file: "music/Yeah, I Said It.mp3",
    playing: false,
  },
  {
    artist: "Rihannah",
    song: "Same Ol Mistakes",
    album: "Single",
    time: 0,
    cover: "/cover/anti.jpg",
    file: "music/Same Ol Mistakes.mp3",
    playing: false,
  },
  {
    artist: "Rihannah",
    song: "Never Ending",
    album: "Single",
    time: 0,
    cover: "/cover/anti.jpg",
    file: "music/Never Ending.mp3",
    playing: false,
  },
  {
    artist: "Rihannah",
    song: "Love on the Brain",
    album: "Single",
    time: 0,
    cover: "/cover/anti.jpg",
    file: "music/Love on the Brain.mp3",
    playing: false,
  },
  {
    artist: "Rihannah",
    song: "Higher",
    album: "Single",
    time: 0,
    cover: "/cover/anti.jpg",
    file: "music/Higher.mp3",
    playing: false,
  },
  {
    artist: "Rihannah",
    song: "Close to You",
    album: "Single",
    time: 0,
    cover: "/cover/anti.jpg",
    file: "music/Close to You.mp3",
    playing: false,
  },
  {
    artist: "Rihannah",
    song: "Goodnight Gotham",
    album: "Single",
    time: 0,
    cover: "/cover/anti.jpg",
    file: "music/Goodnight Gotham.mp3",
    playing: false,
  },
  {
    artist: "Rihannah",
    song: "Pose",
    album: "Single",
    time: 0,
    cover: "/cover/anti.jpg",
    file: "music/Pose.mp3",
    playing: false,
  },
  {
    artist: "Rihannah",
    song: " ",
    album: "Single",
    time: 0,
    cover: "/cover/anti.jpg",
    file: "music/ .mp3",
    playing: false,
  },
  {
    artist: "Rihannah",
    song: "Sex with Me",
    album: "Single",
    time: 0,
    cover: "/cover/anti.jpg",
    file: "music/Sex with Me.mp3",
    playing: false,
  },
];

var featured: any = [
    {
      artist: "Omah Lay",
      song: "Reason",
      album: "Single",
      time: 0,
      cover: "/cover/1.jpg",
      file: "/music/omhlayreason.mp3",
      playing: true,
    },
    {
      artist: "Yarden",
      song: "Wetin",
      album: "Single",
      time: 0,
      cover: "/cover/2.jpg",
      file: "/music/wetin.mp3",
      playing: false,
    },
    {
      artist: "Cinnamon Girl",
      song: "Lana Del Rey",
      album: "Single",
      time: 0,
      cover: "/cover/4.jpg",
      file: "/music/cinnamon.mp3",
      playing: false,
    },
    {
      artist: "Rihannah",
      song: "Consideration (feat. SZA)",
      album: "Single",
      time: 0,
      cover: "/cover/anti.jpg",
      file: "music/Consideration (feat. SZA).mp3",
      playing: false,
    },
    {
      artist: "Rihannah",
      song: "James Joint",
      album: "Single",
      time: 0,
      cover: "/cover/anti.jpg",
      file: "music/James Joint.mp3",
      playing: false,
    },
    {
      artist: "Rihannah",
      song: "Kiss It Better",
      album: "Single",
      time: 0,
      cover: "/cover/anti.jpg",
      file: "music/Kiss It Better.mp3",
      playing: false,
    },
    {
      artist: "Rihannah",
      song: "Work (feat. Drake)",
      album: "Single",
      time: 0,
      cover: "/cover/anti.jpg",
      file: "music/Work (feat. Drake).mp3",
      playing: false,
    },
    {
      artist: "Rihannah",
      song: "Desperado",
      album: "Single",
      time: 0,
      cover: "/cover/anti.jpg",
      file: "music/Desperado.mp3",
      playing: false,
    },
    {
      artist: "Rihannah",
      song: "Woo",
      album: "Single",
      time: 0,
      cover: "/cover/anti.jpg",
      file: "music/Woo.mp3",
      playing: false,
    },
    {
      artist: "Rihannah",
      song: "Needed Me",
      album: "Single",
      time: 0,
      cover: "/cover/anti.jpg",
      file: "music/Needed Me.mp3",
      playing: false,
    },
    {
      artist: "Rihannah",
      song: "Yeah, I Said It",
      album: "Single",
      time: 0,
      cover: "/cover/anti.jpg",
      file: "music/Yeah, I Said It.mp3",
      playing: false,
    },
    {
      artist: "Rihannah",
      song: "Same Ol Mistakes",
      album: "Single",
      time: 0,
      cover: "/cover/anti.jpg",
      file: "music/Same Ol Mistakes.mp3",
      playing: false,
    },
    {
      artist: "Rihannah",
      song: "Never Ending",
      album: "Single",
      time: 0,
      cover: "/cover/anti.jpg",
      file: "music/Never Ending.mp3",
      playing: false,
    },
    {
      artist: "Rihannah",
      song: "Love on the Brain",
      album: "Single",
      time: 0,
      cover: "/cover/anti.jpg",
      file: "music/Love on the Brain.mp3",
      playing: false,
    },
    {
      artist: "Rihannah",
      song: "Higher",
      album: "Single",
      time: 0,
      cover: "/cover/anti.jpg",
      file: "music/Higher.mp3",
      playing: false,
    },
    {
      artist: "Rihannah",
      song: "Close to You",
      album: "Single",
      time: 0,
      cover: "/cover/anti.jpg",
      file: "music/Close to You.mp3",
      playing: false,
    },
    {
      artist: "Rihannah",
      song: "Goodnight Gotham",
      album: "Single",
      time: 0,
      cover: "/cover/anti.jpg",
      file: "music/Goodnight Gotham.mp3",
      playing: false,
    },
    {
      artist: "Rihannah",
      song: "Pose",
      album: "Single",
      time: 0,
      cover: "/cover/anti.jpg",
      file: "music/Pose.mp3",
      playing: false,
    },
    {
      artist: "Rihannah",
      song: "Sex with Me",
      album: "Single",
      time: 0,
      cover: "/cover/anti.jpg",
      file: "music/Sex with Me.mp3",
      playing: false,
    },
  ];

const Queue: any = [
  {
    artist: "Omah Lay",
    song: "Reason",
    album: "Single",
    time: 0,
    cover: "/cover/1.jpg",
    file: "/music/omhlayreason.mp3",
    playing: true,
 
  },
  {
    artist: "Yarden",
    song: "Wetin",
    album: "Single",
    time: 0,
    cover: "/cover/2.jpg",
    file: "/music/wetin.mp3",
    playing: false,
 
  },
  {
    artist: "Lana Del Rey",
    song: "Cinnamon Girls Lanas del de",
    album: "Single",
    time: 0,
    cover: "/cover/4.jpg",
    file: "/music/cinnamon.mp3",
    playing: false,
 
  },
  {
    artist: "Rema",
    song: "Yarden",
    album: "Single",
    time: 0,
    cover: "/cover/3.jpg",
    file: "/music/omhlayreason.mp3",
    playing: false,
  },
];

const playLists: any = [];

const featuredGenres: any = [];

export { allSongs, featured, Queue, playLists, featuredGenres };
